version: '3'

services:

  api:
    container_name: boilerplate_api
    image: node:10
    networks:
      - db
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    env_file:
      - .env

  db:
    container_name: boilerplate_db
    image: mongo
    networks:
      - db
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGO_DATA_DIR: /data/db
    env_file:
      - .env

networks:
  db:

volumes:
  db_data:
